"""Generated by notebooks/document_processing_model.ipynb. Do not edit manually."""
from __future__ import annotations

import logging
import re
import shutil
import subprocess
import tempfile
import unicodedata
from dataclasses import dataclass, field
from io import BytesIO
from pathlib import Path
from typing import Any, Callable, Iterable, Sequence


LOGGER = logging.getLogger(__name__)
PageFallback = Callable[[Path, int], str | None]
ComplexPageDetector = Callable[[Any, Sequence[tuple[Any, ...]]], bool]


@dataclass(slots=True)
class ParserConfig:
    """Runtime options for :class:`DocumentParser`."""

    enable_ocr: bool = True
    ocr_language: str = "vie+eng"
    tesseract_cmd: str | None = None
    ocr_dpi: int = 300
    ocr_timeout_seconds: int = 60
    min_direct_text_chars: int = 40
    min_image_width: int = 160
    min_image_height: int = 80
    min_image_area_ratio: float = 0.015
    scanned_image_area_ratio: float = 0.45
    include_document_title: bool = True
    include_page_headers: bool = True
    advanced_fallback: PageFallback | None = None
    complex_page_detector: ComplexPageDetector | None = None
    table_settings: dict[str, Any] = field(
        default_factory=lambda: {
            "vertical_strategy": "lines",
            "horizontal_strategy": "lines",
            "snap_tolerance": 3,
            "join_tolerance": 3,
            "intersection_tolerance": 3,
        }
    )


@dataclass(slots=True)
class _PageItem:
    top: float
    left: float
    markdown: str
    kind: str


class MarkerPageFallback:
    """
    Convert one zero-based PDF page with Marker through ``marker_single``.

    Marker is intentionally isolated behind this callable because it is a large,
    optional dependency. The command is only executed for pages selected by the
    parser's complex-page detector.
    """

    def __init__(
        self,
        executable: str = "marker_single",
        timeout_seconds: int = 600,
        force_ocr: bool = False,
    ) -> None:
        self.executable = executable
        self.timeout_seconds = timeout_seconds
        self.force_ocr = force_ocr

    def __call__(self, pdf_path: Path, page_index: int) -> str | None:
        executable = shutil.which(self.executable)
        if executable is None:
            LOGGER.warning(
                "Marker fallback skipped: executable '%s' was not found.",
                self.executable,
            )
            return None

        with tempfile.TemporaryDirectory(prefix="marker-page-") as output_dir:
            command = [
                executable,
                str(pdf_path),
                "--page_range",
                str(page_index),
                "--output_format",
                "markdown",
                "--output_dir",
                output_dir,
                "--disable_image_extraction",
            ]
            if self.force_ocr:
                command.append("--force_ocr")

            try:
                subprocess.run(
                    command,
                    check=True,
                    capture_output=True,
                    text=True,
                    timeout=self.timeout_seconds,
                )
            except (OSError, subprocess.SubprocessError) as exc:
                LOGGER.warning(
                    "Marker fallback failed for page %d: %s",
                    page_index + 1,
                    exc,
                )
                return None

            markdown_files = sorted(
                Path(output_dir).rglob("*.md"),
                key=lambda path: path.stat().st_mtime,
                reverse=True,
            )
            if not markdown_files:
                LOGGER.warning(
                    "Marker returned no Markdown for page %d.", page_index + 1
                )
                return None

            return markdown_files[0].read_text(encoding="utf-8").strip() or None


class DocumentParser:
    """Parse PDF and DOCX documents into a combined Markdown string."""

    SUPPORTED_EXTENSIONS = {".pdf", ".docx"}

    def __init__(self, config: ParserConfig | None = None) -> None:
        self.config = config or ParserConfig()
        self._ocr_available: bool | None = None
        self._effective_ocr_language = self.config.ocr_language
        self._ocr_warning_emitted = False

    def parse(self, file_path: str | Path) -> str:
        """Parse a supported document and return normalized Markdown."""
        path = Path(file_path).expanduser().resolve()
        if not path.is_file():
            raise FileNotFoundError(f"Document not found: {path}")

        extension = path.suffix.lower()
        if extension not in self.SUPPORTED_EXTENSIONS:
            supported = ", ".join(sorted(self.SUPPORTED_EXTENSIONS))
            raise ValueError(
                f"Unsupported document type '{extension}'. Supported: {supported}"
            )

        if extension == ".pdf":
            body = self._parse_pdf(path)
        else:
            body = self._parse_docx(path)

        sections = []
        if self.config.include_document_title:
            sections.append(f"# {self._escape_heading(path.stem)}")
        if body:
            sections.append(body)
        return self._join_sections(sections)

    def _parse_pdf(self, path: Path) -> str:
        fitz, pdfplumber = self._load_pdf_dependencies()
        page_sections: list[str] = []

        with fitz.open(path) as pdf_document, pdfplumber.open(path) as plumber_pdf:
            if len(pdf_document) != len(plumber_pdf.pages):
                raise RuntimeError(
                    "PyMuPDF and pdfplumber returned different page counts."
                )

            for page_index, fitz_page in enumerate(pdf_document):
                plumber_page = plumber_pdf.pages[page_index]
                blocks = self._text_blocks(fitz_page)

                if self._should_use_advanced_fallback(fitz_page, blocks):
                    fallback = self.config.advanced_fallback
                    fallback_markdown = fallback(path, page_index) if fallback else None
                    if fallback_markdown:
                        page_body = self._normalize_markdown(fallback_markdown)
                    else:
                        page_body = self._parse_pdf_page(
                            fitz_page, plumber_page, blocks
                        )
                else:
                    page_body = self._parse_pdf_page(
                        fitz_page, plumber_page, blocks
                    )

                if self.config.include_page_headers:
                    page_sections.append(
                        self._join_sections(
                            [f"## Page {page_index + 1}", page_body]
                        )
                    )
                elif page_body:
                    page_sections.append(page_body)

        return self._join_sections(page_sections)

    def _parse_pdf_page(
        self,
        fitz_page: Any,
        plumber_page: Any,
        blocks: Sequence[tuple[Any, ...]],
    ) -> str:
        tables = self._extract_pdf_tables(plumber_page)
        table_boxes = [table["bbox"] for table in tables]
        page_items: list[_PageItem] = []

        for block in blocks:
            x0, y0, x1, y1, text = block[:5]
            block_box = (float(x0), float(y0), float(x1), float(y1))
            if any(self._overlap_ratio(block_box, box) >= 0.35 for box in table_boxes):
                continue
            normalized = self._normalize_text(text)
            if normalized:
                page_items.append(
                    _PageItem(float(y0), float(x0), normalized, "text")
                )

        for table in tables:
            page_items.append(
                _PageItem(
                    float(table["bbox"][1]),
                    float(table["bbox"][0]),
                    self._table_to_markdown(table["rows"]),
                    "table",
                )
            )

        direct_text = "\n".join(
            item.markdown for item in page_items if item.kind in {"text", "table"}
        )
        image_info = self._image_info(fitz_page)

        if self._looks_scanned_page(fitz_page, direct_text, image_info):
            ocr_text = self._ocr_page(fitz_page)
            if ocr_text and not self._is_duplicate_text(ocr_text, direct_text):
                return self._normalize_text(ocr_text)
        else:
            page_items.extend(
                self._ocr_embedded_images(
                    fitz_page=fitz_page,
                    image_info=image_info,
                    table_boxes=table_boxes,
                    direct_text=direct_text,
                )
            )

        page_items.sort(key=lambda item: (round(item.top, 1), item.left))
        return self._join_sections(item.markdown for item in page_items)

    def _extract_pdf_tables(self, plumber_page: Any) -> list[dict[str, Any]]:
        tables: list[dict[str, Any]] = []
        try:
            detected_tables = plumber_page.find_tables(
                table_settings=self.config.table_settings
            )
        except Exception as exc:
            LOGGER.warning(
                "Table detection failed on PDF page %s: %s",
                getattr(plumber_page, "page_number", "?"),
                exc,
            )
            return tables

        for table in detected_tables:
            try:
                rows = table.extract()
            except Exception as exc:
                LOGGER.warning("A detected table could not be extracted: %s", exc)
                continue
            if self._valid_table(rows):
                tables.append({"bbox": tuple(table.bbox), "rows": rows})
        return tables

    def _ocr_embedded_images(
        self,
        fitz_page: Any,
        image_info: Sequence[dict[str, Any]],
        table_boxes: Sequence[tuple[float, float, float, float]],
        direct_text: str,
    ) -> list[_PageItem]:
        if not self._ensure_ocr_available():
            return []

        page_area = max(float(fitz_page.rect.get_area()), 1.0)
        seen_digests: set[bytes] = set()
        items: list[_PageItem] = []

        for image in image_info:
            bbox = tuple(float(value) for value in image.get("bbox", ()))
            if len(bbox) != 4:
                continue

            width = max(bbox[2] - bbox[0], 0.0)
            height = max(bbox[3] - bbox[1], 0.0)
            area_ratio = (width * height) / page_area
            if (
                image.get("width", 0) < self.config.min_image_width
                or image.get("height", 0) < self.config.min_image_height
                or area_ratio < self.config.min_image_area_ratio
            ):
                continue
            if any(self._overlap_ratio(bbox, box) >= 0.5 for box in table_boxes):
                continue

            digest = image.get("digest")
            if digest and digest in seen_digests:
                continue
            if digest:
                seen_digests.add(digest)

            ocr_text = self._ocr_page(fitz_page, clip=bbox)
            if not ocr_text or self._is_duplicate_text(ocr_text, direct_text):
                continue
            items.append(
                _PageItem(
                    top=bbox[1],
                    left=bbox[0],
                    markdown=self._join_sections(
                        ["### OCR image", self._normalize_text(ocr_text)]
                    ),
                    kind="ocr",
                )
            )
        return items

    def _parse_docx(self, path: Path) -> str:
        Document, Paragraph, Table = self._load_docx_dependencies()
        document = Document(path)
        sections: list[str] = []

        for child in document.element.body.iterchildren():
            if child.tag.endswith("}p"):
                paragraph = Paragraph(child, document)
                paragraph_markdown = self._docx_paragraph_to_markdown(paragraph)
                if paragraph_markdown:
                    sections.append(paragraph_markdown)

                for ocr_text in self._ocr_docx_paragraph_images(paragraph):
                    sections.append(
                        self._join_sections(
                            ["### OCR image", self._normalize_text(ocr_text)]
                        )
                    )
            elif child.tag.endswith("}tbl"):
                table = Table(child, document)
                rows = [
                    [self._docx_cell_text(cell) for cell in row.cells]
                    for row in table.rows
                ]
                if self._valid_table(rows):
                    sections.append(self._table_to_markdown(rows))

        return self._join_sections(sections)

    def _docx_paragraph_to_markdown(self, paragraph: Any) -> str:
        text = self._normalize_text(paragraph.text)
        if not text:
            return ""

        style_name = (getattr(paragraph.style, "name", "") or "").strip()
        heading_match = re.match(r"Heading\s+([1-6])$", style_name, re.IGNORECASE)
        if heading_match:
            level = int(heading_match.group(1)) + 1
            return f"{'#' * min(level, 6)} {text}"
        if style_name.lower() == "title":
            return f"## {text}"
        if "list bullet" in style_name.lower():
            return f"- {text}"
        if "list number" in style_name.lower():
            return f"1. {text}"
        return text

    def _docx_cell_text(self, cell: Any) -> str:
        parts: list[str] = []
        for paragraph in cell.paragraphs:
            text = self._normalize_text(paragraph.text)
            if text:
                parts.append(text)
            parts.extend(self._ocr_docx_paragraph_images(paragraph))
        return "<br>".join(self._normalize_text(part) for part in parts if part)

    def _ocr_docx_paragraph_images(self, paragraph: Any) -> list[str]:
        if not self._ensure_ocr_available():
            return []

        try:
            from docx.oxml.ns import qn
            from PIL import Image
        except ImportError:
            return []

        results: list[str] = []
        for blip in paragraph._p.xpath(".//a:blip"):
            relationship_id = blip.get(qn("r:embed"))
            if not relationship_id:
                continue
            image_part = paragraph.part.related_parts.get(relationship_id)
            if image_part is None or not hasattr(image_part, "blob"):
                continue
            try:
                with Image.open(BytesIO(image_part.blob)) as image:
                    if (
                        image.width < self.config.min_image_width
                        or image.height < self.config.min_image_height
                    ):
                        continue
                    text = self._run_tesseract(image.convert("RGB"))
            except Exception as exc:
                LOGGER.warning("DOCX image OCR failed: %s", exc)
                continue
            if text:
                results.append(text)
        return results

    def _text_blocks(self, fitz_page: Any) -> list[tuple[Any, ...]]:
        blocks = fitz_page.get_text("blocks", sort=True)
        return [block for block in blocks if len(block) < 7 or block[6] == 0]

    def _image_info(self, fitz_page: Any) -> list[dict[str, Any]]:
        try:
            return list(fitz_page.get_image_info(hashes=True, xrefs=True))
        except Exception as exc:
            LOGGER.warning("Could not inspect images on PDF page: %s", exc)
            return []

    def _looks_scanned_page(
        self,
        fitz_page: Any,
        direct_text: str,
        image_info: Sequence[dict[str, Any]],
    ) -> bool:
        if not self.config.enable_ocr:
            return False

        text_length = len(re.sub(r"\s+", "", direct_text))
        if text_length == 0:
            return True
        if text_length >= self.config.min_direct_text_chars:
            return False

        page_area = max(float(fitz_page.rect.get_area()), 1.0)
        largest_image_ratio = 0.0
        for image in image_info:
            bbox = image.get("bbox")
            if not bbox or len(bbox) != 4:
                continue
            width = max(float(bbox[2]) - float(bbox[0]), 0.0)
            height = max(float(bbox[3]) - float(bbox[1]), 0.0)
            largest_image_ratio = max(
                largest_image_ratio, (width * height) / page_area
            )
        return largest_image_ratio >= self.config.scanned_image_area_ratio

    def _ocr_page(
        self,
        fitz_page: Any,
        clip: tuple[float, float, float, float] | None = None,
    ) -> str:
        if not self._ensure_ocr_available():
            return ""

        try:
            from PIL import Image

            pixmap = fitz_page.get_pixmap(
                dpi=self.config.ocr_dpi,
                clip=clip,
                alpha=False,
            )
            with Image.open(BytesIO(pixmap.tobytes("png"))) as image:
                return self._run_tesseract(image.convert("RGB"))
        except Exception as exc:
            LOGGER.warning("PDF OCR failed: %s", exc)
            return ""

    def _run_tesseract(self, image: Any) -> str:
        import pytesseract

        try:
            text = pytesseract.image_to_string(
                image,
                lang=self._effective_ocr_language,
                config="--oem 3 --psm 6",
                timeout=self.config.ocr_timeout_seconds,
            )
        except RuntimeError as exc:
            LOGGER.warning("Tesseract timed out or failed: %s", exc)
            return ""
        return self._normalize_text(text)

    def _ensure_ocr_available(self) -> bool:
        if not self.config.enable_ocr:
            return False
        if self._ocr_available is not None:
            return self._ocr_available

        try:
            import pytesseract

            if self.config.tesseract_cmd:
                pytesseract.pytesseract.tesseract_cmd = (
                    self.config.tesseract_cmd
                )
            pytesseract.get_tesseract_version()
            available_languages = set(pytesseract.get_languages(config=""))
            requested_languages = set(self.config.ocr_language.split("+"))
            missing_languages = requested_languages - available_languages
            if missing_languages:
                LOGGER.warning(
                    "Tesseract language data missing: %s.",
                    ", ".join(sorted(missing_languages)),
                )
            usable_languages = [
                language
                for language in self.config.ocr_language.split("+")
                if language in available_languages
            ]
            if not usable_languages:
                raise RuntimeError(
                    "None of the requested Tesseract languages are installed: "
                    f"{self.config.ocr_language}"
                )
            self._effective_ocr_language = "+".join(usable_languages)
            self._ocr_available = True
        except Exception as exc:
            self._ocr_available = False
            if not self._ocr_warning_emitted:
                LOGGER.warning(
                    "OCR disabled because Tesseract is unavailable: %s", exc
                )
                self._ocr_warning_emitted = True
        return self._ocr_available

    def _should_use_advanced_fallback(
        self,
        fitz_page: Any,
        blocks: Sequence[tuple[Any, ...]],
    ) -> bool:
        if self.config.advanced_fallback is None:
            return False
        detector = (
            self.config.complex_page_detector
            or self._default_complex_page_detector
        )
        try:
            return bool(detector(fitz_page, blocks))
        except Exception as exc:
            LOGGER.warning("Complex-page detection failed: %s", exc)
            return False

    @staticmethod
    def _default_complex_page_detector(
        fitz_page: Any,
        blocks: Sequence[tuple[Any, ...]],
    ) -> bool:
        text_blocks = [block for block in blocks if str(block[4]).strip()]
        full_text = " ".join(str(block[4]) for block in text_blocks)
        scientific_symbols = len(
            re.findall(r"[∑∫√≈≠≤≥±∞∂∆∇]|(?:[A-Za-z]\s*[=<>]\s*\S+)", full_text)
        )

        page_width = max(float(fitz_page.rect.width), 1.0)
        left = [
            block
            for block in text_blocks
            if ((float(block[0]) + float(block[2])) / 2) < page_width * 0.45
            and float(block[2]) < page_width * 0.62
        ]
        right = [
            block
            for block in text_blocks
            if ((float(block[0]) + float(block[2])) / 2) > page_width * 0.55
            and float(block[0]) > page_width * 0.38
        ]
        multi_column = len(left) >= 3 and len(right) >= 3
        return scientific_symbols >= 4 or multi_column

    @staticmethod
    def _valid_table(rows: Sequence[Sequence[Any]] | None) -> bool:
        if not rows or len(rows) < 2:
            return False
        max_columns = max((len(row) for row in rows), default=0)
        populated_cells = sum(
            1 for row in rows for cell in row if str(cell or "").strip()
        )
        return max_columns >= 2 and populated_cells >= 4

    def _table_to_markdown(self, rows: Sequence[Sequence[Any]]) -> str:
        width = max(len(row) for row in rows)
        normalized_rows = [
            [self._escape_table_cell(row[index] if index < len(row) else "") for index in range(width)]
            for row in rows
        ]
        header = normalized_rows[0]
        separator = ["---"] * width
        markdown_rows = [header, separator, *normalized_rows[1:]]
        return "\n".join(
            "| " + " | ".join(row) + " |" for row in markdown_rows
        )

    def _escape_table_cell(self, value: Any) -> str:
        text = self._normalize_text("" if value is None else str(value))
        return text.replace("|", r"\|").replace("\n", "<br>")

    @staticmethod
    def _overlap_ratio(
        first: tuple[float, float, float, float],
        second: tuple[float, float, float, float],
    ) -> float:
        x0 = max(first[0], second[0])
        y0 = max(first[1], second[1])
        x1 = min(first[2], second[2])
        y1 = min(first[3], second[3])
        intersection = max(x1 - x0, 0.0) * max(y1 - y0, 0.0)
        first_area = max(first[2] - first[0], 0.0) * max(
            first[3] - first[1], 0.0
        )
        return intersection / max(first_area, 1.0)

    def _is_duplicate_text(self, candidate: str, existing: str) -> bool:
        candidate_key = self._text_key(candidate)
        existing_key = self._text_key(existing)
        if not candidate_key or not existing_key:
            return False
        if candidate_key in existing_key or existing_key in candidate_key:
            return True
        candidate_tokens = set(candidate_key.split())
        existing_tokens = set(existing_key.split())
        if not candidate_tokens:
            return False
        return (
            len(candidate_tokens & existing_tokens) / len(candidate_tokens)
        ) >= 0.8

    @staticmethod
    def _text_key(text: str) -> str:
        return re.sub(r"[^\w]+", " ", text.casefold()).strip()

    @staticmethod
    def _normalize_text(text: Any) -> str:
        value = unicodedata.normalize("NFC", str(text or "")).replace("\x00", "")
        lines = [re.sub(r"[ \t]+", " ", line).strip() for line in value.splitlines()]
        normalized: list[str] = []
        previous_blank = False
        for line in lines:
            is_blank = not line
            if is_blank and previous_blank:
                continue
            normalized.append(line)
            previous_blank = is_blank
        return "\n".join(normalized).strip()

    def _normalize_markdown(self, markdown: str) -> str:
        return self._normalize_text(markdown)

    @staticmethod
    def _escape_heading(text: str) -> str:
        return text.replace("#", r"\#").strip()

    @staticmethod
    def _join_sections(sections: Iterable[str]) -> str:
        return "\n\n".join(section.strip() for section in sections if section and section.strip())

    @staticmethod
    def _load_pdf_dependencies() -> tuple[Any, Any]:
        try:
            import fitz
            import pdfplumber
        except ImportError as exc:
            raise RuntimeError(
                "PDF parsing requires PyMuPDF and pdfplumber. "
                "Install dependencies from requirements.txt."
            ) from exc
        return fitz, pdfplumber

    @staticmethod
    def _load_docx_dependencies() -> tuple[Any, Any, Any]:
        try:
            from docx import Document
            from docx.table import Table
            from docx.text.paragraph import Paragraph
        except ImportError as exc:
            raise RuntimeError(
                "DOCX parsing requires python-docx. "
                "Install dependencies from requirements-document-parser.txt."
            ) from exc
        return Document, Paragraph, Table

import re
import unicodedata
from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class _MarkdownLine:
    text: str
    protected: bool = False


class DataCleaner:
    """Clean parser output while preserving Markdown structure."""

    _PHONE_CANDIDATE_RE = re.compile(
        r"""
        (?<![\w])
        (?:\+[\t .()-]*)?
        (?:[0-9OoIiLl|][\t .()/:-]*){8,15}
        (?![\w])
        """,
        re.VERBOSE,
    )
    _PHONE_OCR_TRANSLATION = str.maketrans(
        {
            "O": "0",
            "o": "0",
            "I": "1",
            "i": "1",
            "L": "1",
            "l": "1",
            "|": "1",
        }
    )
    _FENCE_RE = re.compile(r"^\s*(`{3,}|~{3,})")
    _INDENTED_CODE_RE = re.compile(r"^(?: {4}|\t)")
    _HEADING_RE = re.compile(r"^\s{0,3}#{1,6}(?:\s|$)")
    _LIST_RE = re.compile(r"^\s*(?:[-+*•]\s+|\d+[.)]\s+)")
    _BLOCK_QUOTE_RE = re.compile(r"^\s*>")
    _THEMATIC_BREAK_RE = re.compile(r"^\s{0,3}(?:([-*_])\s*){3,}$")
    _HTML_BLOCK_RE = re.compile(
        r"^\s*</?(?:table|thead|tbody|tr|td|th|div|pre|figure|section)\b",
        re.IGNORECASE,
    )
    _LATEX_BEGIN_RE = re.compile(
        r"\\begin\{(equation\*?|align\*?|aligned|gather\*?|multline\*?|"
        r"cases|matrix|pmatrix|bmatrix|vmatrix|Vmatrix|split)\}"
    )

    @classmethod
    def clean_markdown_text(cls, raw_text: str) -> str:
        """
        Remove junk controls, repair phone-number OCR, and join broken lines.

        Markdown tables, fenced code, and display-math blocks are excluded from
        line joining. Formula and code contents are also excluded from OCR
        substitutions.
        """
        if not isinstance(raw_text, str):
            raise TypeError("raw_text must be a string")
        if not raw_text:
            return ""

        text = cls._remove_control_characters(raw_text)
        lines = cls._mark_protected_lines(text.split("\n"))
        corrected_lines = [
            line
            if line.protected
            else _MarkdownLine(cls._repair_phone_numbers(line.text))
            for line in lines
        ]
        return cls._join_broken_lines(corrected_lines).strip("\n")

    @staticmethod
    def _remove_control_characters(text: str) -> str:
        text = text.replace("\r\n", "\n").replace("\r", "\n")
        cleaned: list[str] = []
        for character in text:
            if character in {"\n", "\t"}:
                cleaned.append(character)
                continue
            if unicodedata.category(character) == "Cc":
                continue
            if character in {"\ufeff", "\u200b", "\u2060"}:
                continue
            cleaned.append(character)
        return "".join(cleaned)

    @classmethod
    def _repair_phone_numbers(cls, line: str) -> str:
        def replace(match: re.Match[str]) -> str:
            candidate = match.group(0)
            ambiguous_count = sum(
                character in "OoIiLl|" for character in candidate
            )
            actual_digit_count = sum(character.isdigit() for character in candidate)
            if ambiguous_count == 0 or actual_digit_count < 5:
                return candidate

            repaired = candidate.translate(cls._PHONE_OCR_TRANSLATION)
            digit_count = sum(character.isdigit() for character in repaired)
            if not 8 <= digit_count <= 15:
                return candidate
            return repaired

        return cls._PHONE_CANDIDATE_RE.sub(replace, line)

    @classmethod
    def _mark_protected_lines(cls, lines: list[str]) -> list[_MarkdownLine]:
        marked: list[_MarkdownLine] = []
        fence_marker: str | None = None
        math_mode: str | None = None
        latex_environment: str | None = None

        for line in lines:
            stripped = line.strip()

            if cls._INDENTED_CODE_RE.match(line):
                marked.append(_MarkdownLine(line, protected=True))
                continue

            if fence_marker is not None:
                marked.append(_MarkdownLine(line, protected=True))
                if re.match(rf"^\s*{re.escape(fence_marker)}", line):
                    fence_marker = None
                continue

            fence_match = cls._FENCE_RE.match(line)
            if fence_match:
                marker = fence_match.group(1)
                fence_marker = marker[0] * len(marker)
                marked.append(_MarkdownLine(line, protected=True))
                continue

            if latex_environment is not None:
                marked.append(_MarkdownLine(line, protected=True))
                if rf"\end{{{latex_environment}}}" in line:
                    latex_environment = None
                continue

            latex_match = cls._LATEX_BEGIN_RE.search(line)
            if latex_match:
                environment = latex_match.group(1)
                marked.append(_MarkdownLine(line, protected=True))
                if rf"\end{{{environment}}}" not in line:
                    latex_environment = environment
                continue

            if math_mode is not None:
                marked.append(_MarkdownLine(line, protected=True))
                if math_mode in line:
                    math_mode = None
                continue

            if stripped.startswith(r"\["):
                marked.append(_MarkdownLine(line, protected=True))
                if r"\]" not in stripped[2:]:
                    math_mode = r"\]"
                continue

            if "$$" in line:
                marked.append(_MarkdownLine(line, protected=True))
                if line.count("$$") % 2 == 1:
                    math_mode = "$$"
                continue

            marked.append(_MarkdownLine(line))

        return marked

    @classmethod
    def _join_broken_lines(cls, lines: list[_MarkdownLine]) -> str:
        output: list[str] = []
        index = 0

        while index < len(lines):
            current = lines[index]
            combined = current.text

            while index + 1 < len(lines):
                following = lines[index + 1]
                if not cls._should_join(current, combined, following):
                    break
                combined = cls._join_pair(combined, following.text)
                index += 1
                current = _MarkdownLine(combined, protected=False)

            output.append(combined)
            index += 1

        return "\n".join(output)

    @classmethod
    def _should_join(
        cls,
        current: _MarkdownLine,
        combined_text: str,
        following: _MarkdownLine,
    ) -> bool:
        if current.protected or following.protected:
            return False
        if not combined_text.strip() or not following.text.strip():
            return False
        if cls._is_table_line(combined_text) or cls._is_table_line(following.text):
            return False
        if cls._is_non_joinable_block(combined_text):
            return False
        if cls._starts_markdown_block(following.text):
            return False
        if cls._has_explicit_markdown_break(combined_text):
            return False
        return not cls._ends_with_punctuation(combined_text)

    @classmethod
    def _is_non_joinable_block(cls, line: str) -> bool:
        return bool(
            cls._HEADING_RE.match(line)
            or cls._BLOCK_QUOTE_RE.match(line)
            or cls._THEMATIC_BREAK_RE.match(line)
            or cls._HTML_BLOCK_RE.match(line)
        )

    @classmethod
    def _starts_markdown_block(cls, line: str) -> bool:
        return bool(
            cls._HEADING_RE.match(line)
            or cls._LIST_RE.match(line)
            or cls._BLOCK_QUOTE_RE.match(line)
            or cls._THEMATIC_BREAK_RE.match(line)
            or cls._HTML_BLOCK_RE.match(line)
            or cls._is_table_line(line)
        )

    @staticmethod
    def _is_table_line(line: str) -> bool:
        stripped = line.strip()
        return (
            stripped.startswith("|")
            and stripped.endswith("|")
            and stripped.count("|") >= 2
        )

    @staticmethod
    def _has_explicit_markdown_break(line: str) -> bool:
        return line.endswith("  ") or line.rstrip().endswith("\\")

    @staticmethod
    def _ends_with_punctuation(line: str) -> bool:
        stripped = line.rstrip()
        stripped = re.sub(r"(?:\*\*|__|~~|`)+$", "", stripped).rstrip()
        if not stripped:
            return True
        return unicodedata.category(stripped[-1]).startswith("P")

    @staticmethod
    def _join_pair(first: str, second: str) -> str:
        left = first.rstrip()
        right = second.strip()
        if not left or not right:
            return left + right
        if right[0] in ",.;:!?)]}":
            return left + right
        return f"{left} {right}"


def clean_markdown_text(raw_text: str) -> str:
    """Convenience wrapper for :meth:`DataCleaner.clean_markdown_text`."""
    return DataCleaner.clean_markdown_text(raw_text)

import re
import unicodedata
from dataclasses import dataclass
from typing import Iterable


@dataclass(frozen=True, slots=True)
class _MarkdownTable:
    start: int
    end: int
    heading: str
    headers: tuple[str, ...]
    rows: tuple[tuple[str, ...], ...]

    def text_rows(self) -> list[str]:
        rendered: list[str] = []
        for row in self.rows:
            if len(row) == 2:
                rendered.append(f"{row[0]}: {row[1]}")
                continue

            cells = []
            for index, value in enumerate(row):
                if not value:
                    continue
                header = self.headers[index] if index < len(self.headers) else ""
                cells.append(f"{header}: {value}" if header else value)
            if cells:
                rendered.append(", ".join(cells))
        return rendered


class ProfileExtractor:
    """Extract a learner-needs profile from cleaned Markdown."""

    OUTPUT_FIELDS = (
        "ho_ten",
        "email",
        "so_dien_thoai",
        "kien_thuc_nen_tang",
        "muc_tieu_hoc_tap",
        "hinh_thuc_hoc",
        "thoi_gian_hoc",
    )

    EMAIL_RE = re.compile(
        r"(?<![\w.+-])"
        r"[A-Z0-9.!#$%&'*+/=?^_`{|}~-]+"
        r"@[A-Z0-9-]+(?:\.[A-Z0-9-]+)+"
        r"(?![\w.-])",
        re.IGNORECASE,
    )
    PHONE_RE = re.compile(
        r"(?<!\d)"
        r"(?P<phone>(?:\+?84|0)(?:[\s.\-()]?\d){9})"
        r"(?!\d)"
    )
    HEADING_RE = re.compile(r"^\s{0,3}(#{1,6})\s+(.+?)\s*$")
    TABLE_SEPARATOR_RE = re.compile(r"^:?-{3,}:?$")

    NAME_LABEL_ANCHORS = (
        "họ và tên",
        "họ tên",
        "họ tên học viên",
        "tên học viên",
        "tên người học",
        "full name",
    )
    NAME_PROSE_RE = re.compile(
        r"(?:"
        r"tôi\s+tên\s+là|"
        r"tên\s+tôi\s+là|"
        r"họ\s*(?:và\s*)?tên(?:\s+học\s+viên)?"
        r")"
        r"\s*(?::|：|-|\blà\b)?\s*"
        r"(?P<name>[^,;|.\n]+)",
        re.IGNORECASE,
    )

    FIELD_RULES = {
        "kien_thuc_nen_tang": {
            "labels": (
                "kiến thức nền tảng",
                "kiến thức hiện tại",
                "trình độ hiện tại",
                "năng lực hiện có",
                "nền tảng chuyên môn",
                "trình độ chuyên môn",
                "kinh nghiệm hiện tại",
                "nghề nghiệp",
                "nhóm kỹ năng",
            ),
            "sections": (
                "kiến thức và trình độ hiện tại",
                "kiến thức nền tảng",
                "trình độ hiện tại",
                "năng lực hiện có",
                "nền tảng chuyên môn",
                "kinh nghiệm",
            ),
            "paragraphs": (
                "hiện tại tôi",
                "hiện đang",
                "công việc chủ yếu",
                "đã từng học",
                "đã có kiến thức",
                "có kinh nghiệm",
                "sinh viên",
                "developer",
                "lập trình viên",
            ),
        },
        "muc_tieu_hoc_tap": {
            "labels": (
                "mục tiêu học tập",
                "mục tiêu cụ thể",
                "kỹ năng mong muốn",
                "mong muốn đạt được",
                "nhu cầu đào tạo",
                "định hướng học tập",
                "nội dung muốn học",
            ),
            "sections": (
                "mục tiêu học tập",
                "kỹ năng mong muốn",
                "nhu cầu đào tạo",
                "định hướng học tập",
                "mong muốn đạt được",
            ),
            "paragraphs": (
                "mục tiêu của tôi",
                "mục tiêu cụ thể",
                "tôi muốn",
                "mong muốn",
                "muốn chuyển",
                "trong thời gian tới",
                "sau khóa học",
            ),
        },
        "hinh_thuc_hoc": {
            "labels": (
                "hình thức học mong muốn",
                "hình thức học",
                "hình thức ưu tiên",
                "hình thức",
                "địa điểm học",
                "địa điểm hiện tại",
                "khu vực học",
                "khu vực",
            ),
            "sections": (
                "hình thức học mong muốn",
                "hình thức học",
                "địa điểm học",
                "khu vực học",
            ),
            "paragraphs": (
                "về hình thức học",
                "ưu tiên học",
                "học online",
                "học offline",
                "trực tuyến",
                "trực tiếp",
                "khu vực",
            ),
        },
        "thoi_gian_hoc": {
            "labels": (
                "thời gian có thể học",
                "thời gian phù hợp",
                "thời gian học",
                "khung giờ",
                "lịch học",
                "ngày cuối tuần",
                "thời gian có thể sắp xếp",
            ),
            "sections": (
                "thời gian có thể học",
                "thời gian học",
                "khung giờ học",
                "lịch học",
            ),
            "paragraphs": (
                "thời gian có thể",
                "có thể sắp xếp",
                "khung giờ",
                "tối thứ",
                "sáng thứ",
                "chiều thứ",
                "cuối tuần",
                "chủ nhật",
            ),
        },
    }

    def extract(self, cleaned_text: str) -> dict[str, str]:
        """Return a stable dictionary containing all supported profile fields."""
        if not isinstance(cleaned_text, str):
            raise TypeError("cleaned_text must be a string")

        result = {field: "" for field in self.OUTPUT_FIELDS}
        if not cleaned_text.strip():
            return result

        lines = cleaned_text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
        tables = self._parse_tables(lines)
        flattened_lines = self._flatten_tables(lines, tables)
        plain_text = "\n".join(self._plain_markdown(line) for line in flattened_lines)

        email_match = self.EMAIL_RE.search(plain_text)
        if email_match:
            result["email"] = email_match.group(0)

        phone_match = self.PHONE_RE.search(plain_text)
        if phone_match:
            result["so_dien_thoai"] = self._normalize_phone_display(
                phone_match.group("phone")
            )

        result["ho_ten"] = self._extract_name(flattened_lines, tables)

        sections = self._extract_sections(flattened_lines)
        paragraphs = self._extract_paragraphs(flattened_lines)
        for field, rules in self.FIELD_RULES.items():
            candidates: list[str] = []
            candidates.extend(
                self._values_from_sections(sections, rules["sections"])
            )
            candidates.extend(
                self._values_from_paragraphs(paragraphs, rules["paragraphs"])
            )
            candidates.extend(
                self._values_from_labels(flattened_lines, rules["labels"])
            )
            candidates.extend(
                self._values_from_tables(tables, rules["labels"], rules["sections"])
            )
            result[field] = self._merge_candidates(candidates)

        return result

    def _extract_name(
        self,
        lines: list[str],
        tables: list[_MarkdownTable],
    ) -> str:
        candidates = self._values_from_labels(lines, self.NAME_LABEL_ANCHORS)
        candidates.extend(
            self._values_from_tables(tables, self.NAME_LABEL_ANCHORS, ())
        )
        for candidate in candidates:
            name = self._clean_name(candidate)
            if self._is_valid_name(name):
                return name

        plain_text = "\n".join(self._plain_markdown(line) for line in lines)
        for match in self.NAME_PROSE_RE.finditer(plain_text):
            name = self._clean_name(match.group("name"))
            if self._is_valid_name(name):
                return name
        return ""

    def _parse_tables(self, lines: list[str]) -> list[_MarkdownTable]:
        tables: list[_MarkdownTable] = []
        index = 0
        last_heading = ""

        while index < len(lines):
            heading_match = self.HEADING_RE.match(lines[index])
            if heading_match:
                last_heading = self._plain_markdown(heading_match.group(2))

            if (
                index + 1 < len(lines)
                and self._looks_like_table_row(lines[index])
                and self._is_table_separator_row(lines[index + 1])
            ):
                end = index + 2
                while end < len(lines) and self._looks_like_table_row(lines[end]):
                    end += 1

                headers = tuple(self._split_table_row(lines[index]))
                rows = tuple(
                    tuple(self._split_table_row(line))
                    for line in lines[index + 2 : end]
                    if not self._is_table_separator_row(line)
                )
                tables.append(
                    _MarkdownTable(
                        start=index,
                        end=end,
                        heading=last_heading,
                        headers=headers,
                        rows=rows,
                    )
                )
                index = end
                continue
            index += 1

        return tables

    def _flatten_tables(
        self,
        lines: list[str],
        tables: list[_MarkdownTable],
    ) -> list[str]:
        table_by_start = {table.start: table for table in tables}
        flattened: list[str] = []
        index = 0

        while index < len(lines):
            table = table_by_start.get(index)
            if table is None:
                flattened.append(lines[index])
                index += 1
                continue
            flattened.extend(table.text_rows())
            index = table.end
        return flattened

    def _extract_sections(
        self,
        lines: list[str],
    ) -> list[tuple[str, str]]:
        headings: list[tuple[int, int, str]] = []
        for index, line in enumerate(lines):
            match = self.HEADING_RE.match(line)
            if match:
                headings.append(
                    (index, len(match.group(1)), self._plain_markdown(match.group(2)))
                )

        sections: list[tuple[str, str]] = []
        for position, (start, level, heading) in enumerate(headings):
            end = len(lines)
            for next_start, next_level, _ in headings[position + 1 :]:
                if next_level <= level:
                    end = next_start
                    break
            value = self._format_lines(lines[start + 1 : end])
            if value:
                sections.append((heading, value))
        return sections

    def _extract_paragraphs(self, lines: list[str]) -> list[str]:
        paragraphs: list[str] = []
        current: list[str] = []

        for line in lines:
            if not line.strip():
                value = self._format_lines(current)
                if value:
                    paragraphs.append(value)
                current = []
                continue
            if self.HEADING_RE.match(line):
                value = self._format_lines(current)
                if value:
                    paragraphs.append(value)
                current = []
                continue
            current.append(line)

        value = self._format_lines(current)
        if value:
            paragraphs.append(value)
        return paragraphs

    def _values_from_sections(
        self,
        sections: list[tuple[str, str]],
        anchors: Iterable[str],
    ) -> list[str]:
        return [
            value
            for heading, value in sections
            if self._matches_any_anchor(heading, anchors)
        ]

    def _values_from_paragraphs(
        self,
        paragraphs: list[str],
        anchors: Iterable[str],
    ) -> list[str]:
        return [
            paragraph
            for paragraph in paragraphs
            if self._contains_any_anchor(paragraph, anchors)
        ]

    def _values_from_labels(
        self,
        lines: Iterable[str],
        anchors: Iterable[str],
    ) -> list[str]:
        values: list[str] = []
        for line in lines:
            plain_line = self._plain_markdown(line)
            label, value = self._split_labeled_value(plain_line)
            if (
                label
                and value
                and self._matches_any_anchor(label, anchors)
            ):
                values.append(value)
        return values

    def _values_from_tables(
        self,
        tables: list[_MarkdownTable],
        label_anchors: Iterable[str],
        section_anchors: Iterable[str],
    ) -> list[str]:
        values: list[str] = []
        for table in tables:
            if self._matches_any_anchor(table.heading, section_anchors):
                values.append("; ".join(table.text_rows()))

            for row in table.rows:
                if len(row) < 2:
                    continue
                label = row[0]
                if self._matches_any_anchor(label, label_anchors):
                    values.append("; ".join(cell for cell in row[1:] if cell))
        return values

    @classmethod
    def _split_table_row(cls, line: str) -> list[str]:
        stripped = line.strip()
        if stripped.startswith("|"):
            stripped = stripped[1:]
        if stripped.endswith("|"):
            stripped = stripped[:-1]

        cells: list[str] = []
        current: list[str] = []
        escaped = False
        for character in stripped:
            if escaped:
                current.append(character)
                escaped = False
            elif character == "\\":
                escaped = True
                current.append(character)
            elif character == "|":
                cells.append(cls._plain_markdown("".join(current)))
                current = []
            else:
                current.append(character)
        cells.append(cls._plain_markdown("".join(current)))
        return cells

    @classmethod
    def _is_table_separator_row(cls, line: str) -> bool:
        cells = cls._split_table_row(line)
        return bool(cells) and all(
            cls.TABLE_SEPARATOR_RE.fullmatch(cell.replace(" ", ""))
            for cell in cells
        )

    @staticmethod
    def _looks_like_table_row(line: str) -> bool:
        stripped = line.strip()
        return (
            stripped.startswith("|")
            and stripped.endswith("|")
            and stripped.count("|") >= 2
        )

    @classmethod
    def _format_lines(cls, lines: Iterable[str]) -> str:
        parts = [cls._plain_markdown(line) for line in lines]
        return "; ".join(part for part in parts if part)

    @staticmethod
    def _split_labeled_value(line: str) -> tuple[str, str]:
        match = re.match(r"^(.{1,80}?)(?::|：)\s*(.+)$", line)
        if not match:
            return "", ""
        return match.group(1).strip(), match.group(2).strip()

    @classmethod
    def _plain_markdown(cls, text: str) -> str:
        value = text.strip()
        value = re.sub(r"^\s{0,3}#{1,6}\s+", "", value)
        value = re.sub(r"^\s*(?:[-+*•]\s+|\d+[.)]\s+|>\s*)", "", value)
        value = re.sub(r"!\[([^\]]*)\]\([^)]+\)", r"\1", value)
        value = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", value)
        value = re.sub(r"</?br\s*/?>", "; ", value, flags=re.IGNORECASE)
        value = re.sub(r"(\*\*|__|~~|`)", "", value)
        value = value.replace(r"\|", "|")
        return re.sub(r"\s+", " ", value).strip()

    @classmethod
    def _matches_any_anchor(
        cls,
        value: str,
        anchors: Iterable[str],
    ) -> bool:
        normalized = cls._normalize_for_match(value)
        return any(
            (anchor_value := cls._normalize_for_match(anchor))
            and (
                normalized == anchor_value
                or normalized.startswith(f"{anchor_value} ")
                or anchor_value in normalized
            )
            for anchor in anchors
        )

    @classmethod
    def _contains_any_anchor(
        cls,
        value: str,
        anchors: Iterable[str],
    ) -> bool:
        normalized = f" {cls._normalize_for_match(value)} "
        return any(
            f" {cls._normalize_for_match(anchor)} " in normalized
            for anchor in anchors
        )

    @staticmethod
    def _normalize_for_match(value: str) -> str:
        decomposed = unicodedata.normalize("NFD", value.casefold())
        without_marks = "".join(
            character
            for character in decomposed
            if unicodedata.category(character) != "Mn"
        )
        without_marks = without_marks.replace("đ", "d")
        return re.sub(r"[^a-z0-9]+", " ", without_marks).strip()

    @classmethod
    def _clean_name(cls, value: str) -> str:
        name = cls._plain_markdown(value)
        name = re.split(
            r"\s+(?:hiện|đang|sinh\s+sống|làm\s+việc|email)\b",
            name,
            maxsplit=1,
            flags=re.IGNORECASE,
        )[0]
        return name.strip(" :-")

    @staticmethod
    def _is_valid_name(value: str) -> bool:
        words = value.split()
        if not 2 <= len(words) <= 8 or any(character.isdigit() for character in value):
            return False
        return all(
            character.isalpha() or character in " .'-"
            for character in value
        )

    @staticmethod
    def _normalize_phone_display(phone: str) -> str:
        return re.sub(r"\s+", " ", phone).strip()

    @classmethod
    def _merge_candidates(cls, candidates: Iterable[str]) -> str:
        merged: list[str] = []
        normalized_values: list[str] = []

        for candidate in candidates:
            value = cls._plain_markdown(candidate).strip(" ;")
            normalized = cls._normalize_for_match(value)
            if not normalized:
                continue

            if any(normalized in existing for existing in normalized_values):
                continue

            contained_indexes = [
                index
                for index, existing in enumerate(normalized_values)
                if existing in normalized
            ]
            for index in reversed(contained_indexes):
                del merged[index]
                del normalized_values[index]

            merged.append(value)
            normalized_values.append(normalized)

        return "; ".join(merged)


def extract_profile(cleaned_text: str) -> dict[str, str]:
    """Convenience wrapper for :class:`ProfileExtractor`."""
    return ProfileExtractor().extract(cleaned_text)

import re
from dataclasses import dataclass
from typing import Iterable



@dataclass(frozen=True, slots=True)
class _CourseSection:
    start: int
    end: int
    level: int
    title: str
    lines: tuple[str, ...]


class CourseExtractor(ProfileExtractor):
    """Extract structured course information from cleaned Markdown."""

    OUTPUT_FIELDS = (
        "ten_khoa_hoc",
        "noi_dung_dao_tao",
        "yeu_cau_dau_vao",
        "hinh_thuc_to_chuc",
        "thoi_luong_lich_hoc",
    )

    COURSE_NAME_ANCHORS = (
        "tên khóa học",
        "tên chương trình",
        "tên học phần",
        "course name",
    )
    CONTENT_ANCHORS = (
        "nội dung đào tạo",
        "nội dung khóa học",
        "nội dung chi tiết",
        "nội dung chi tiết theo chương",
        "nội dung chương trình",
        "chương trình đào tạo",
        "chương trình học",
        "mục tiêu học tập",
        "mục tiêu đào tạo",
        "chuẩn đầu ra",
        "kỹ năng đầu ra",
        "kỹ năng đạt được",
        "kết quả học tập",
        "learning outcomes",
        "syllabus",
        "curriculum",
    )
    REQUIREMENT_ANCHORS = (
        "yêu cầu đầu vào",
        "điều kiện đầu vào",
        "điều kiện tiên quyết",
        "kiến thức tiên quyết",
        "kỹ năng tối thiểu",
        "trình độ tối thiểu",
        "trình độ phù hợp",
        "đối tượng học viên phù hợp",
        "đối tượng tham gia",
        "prerequisite",
        "prerequisites",
    )
    FORMAT_ANCHORS = (
        "hình thức tổ chức",
        "hình thức đào tạo",
        "hình thức học",
        "phương thức học",
        "địa điểm học",
        "địa điểm tổ chức",
        "khu vực học",
        "khu vực tổ chức",
        "khu vực",
    )
    DURATION_ANCHORS = (
        "thời lượng",
        "thời lượng khóa học",
        "thời gian đào tạo",
        "thời gian học",
        "lịch học",
        "khung giờ học",
        "số buổi",
        "thời khóa biểu",
    )
    OTHER_SECTION_ANCHORS = (
        "thông tin khóa học",
        "mô tả khóa học",
        "tổng quan khóa học",
        "phương pháp đánh giá",
        "hình thức đánh giá",
        "tài liệu tham khảo",
        "giảng viên",
        "học phí",
        "chứng chỉ",
        "ghi chú",
        "ghi chú bổ sung",
        "ghi chú bổ sung và thông tin ngoài lề",
        "nội dung giải thích thêm",
        "thông tin ngoài lề",
    )
    PAGE_HEADING_RE = re.compile(r"^(?:page|trang)\s+\d+$", re.IGNORECASE)
    NUMBERED_HEADING_RE = re.compile(
        r"^\s*(?P<number>\d+(?:\.\d+)*)[.)]?\s+(?P<title>.+?)\s*$"
    )

    def extract(self, cleaned_text: str) -> dict[str, str]:
        """Return course information using stable snake_case keys."""
        if not isinstance(cleaned_text, str):
            raise TypeError("cleaned_text must be a string")

        result = {field: "" for field in self.OUTPUT_FIELDS}
        if not cleaned_text.strip():
            return result

        lines = cleaned_text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
        tables = self._parse_tables(lines)
        flattened_lines = self._flatten_tables(lines, tables)
        sections = self._extract_course_sections(flattened_lines)

        result["ten_khoa_hoc"] = self._extract_course_name(
            flattened_lines, tables
        )
        result["noi_dung_dao_tao"] = self._extract_block_field(
            sections=sections,
            lines=flattened_lines,
            tables=tables,
            section_anchors=self.CONTENT_ANCHORS,
            label_anchors=self.CONTENT_ANCHORS,
            preserve_section_titles=True,
        )
        result["yeu_cau_dau_vao"] = self._extract_block_field(
            sections=sections,
            lines=flattened_lines,
            tables=tables,
            section_anchors=self.REQUIREMENT_ANCHORS,
            label_anchors=self.REQUIREMENT_ANCHORS,
        )
        result["hinh_thuc_to_chuc"] = self._extract_block_field(
            sections=sections,
            lines=flattened_lines,
            tables=tables,
            section_anchors=self.FORMAT_ANCHORS,
            label_anchors=self.FORMAT_ANCHORS,
        )
        result["thoi_luong_lich_hoc"] = self._extract_block_field(
            sections=sections,
            lines=flattened_lines,
            tables=tables,
            section_anchors=self.DURATION_ANCHORS,
            label_anchors=self.DURATION_ANCHORS,
        )
        return result

    def _extract_course_name(
        self,
        lines: list[str],
        tables: list[_MarkdownTable],
    ) -> str:
        candidates = self._values_from_labels(lines, self.COURSE_NAME_ANCHORS)
        candidates.extend(
            self._values_from_tables(tables, self.COURSE_NAME_ANCHORS, ())
        )
        for candidate in candidates:
            value = self._plain_markdown(candidate).strip(" :-")
            if self._is_valid_course_name(value):
                return value

        for line in lines:
            value = self._plain_markdown(line)
            normalized = self._normalize_for_match(value)
            if (
                not value
                or self.PAGE_HEADING_RE.fullmatch(value)
                or self._is_metadata_line(value)
                or self._detect_structural_heading(line) is not None
                or value.startswith("|")
                or "_" in value
            ):
                continue
            if self._is_valid_course_name(value):
                return value
        return ""

    def _extract_block_field(
        self,
        sections: list[_CourseSection],
        lines: list[str],
        tables: list[_MarkdownTable],
        section_anchors: Iterable[str],
        label_anchors: Iterable[str],
        preserve_section_titles: bool = False,
    ) -> str:
        selected_sections = self._select_sections(sections, section_anchors)
        section_values: list[str] = []
        for section in selected_sections:
            body = self._render_block(section.lines)
            if not body:
                continue
            if preserve_section_titles:
                section_values.append(f"{section.title}:\n{body}")
            else:
                section_values.append(body)

        label_values = self._values_from_labels(lines, label_anchors)
        label_values.extend(
            self._values_from_tables(tables, label_anchors, section_anchors)
        )

        if section_values:
            additional = self._deduplicate_values(
                label_values,
                existing_values=section_values,
            )
            return "\n\n".join([*section_values, *additional]).strip()

        structured_values = self._deduplicate_values(label_values)
        if structured_values:
            return "\n\n".join(structured_values).strip()

        paragraph_values = self._paragraph_fallback(lines, label_anchors)
        return "\n\n".join(self._deduplicate_values(paragraph_values)).strip()

    def _extract_course_sections(self, lines: list[str]) -> list[_CourseSection]:
        headings: list[tuple[int, int, str]] = []
        for index, line in enumerate(lines):
            heading = self._detect_structural_heading(line)
            if heading is not None:
                level, title = heading
                headings.append((index, level, title))

        sections: list[_CourseSection] = []
        for position, (start, level, title) in enumerate(headings):
            end = len(lines)
            for next_start, next_level, _ in headings[position + 1 :]:
                if next_level <= level:
                    end = next_start
                    break

            body_lines = tuple(
                line
                for line in lines[start + 1 : end]
                if not self._is_page_heading(line)
            )
            sections.append(
                _CourseSection(
                    start=start,
                    end=end,
                    level=level,
                    title=title,
                    lines=body_lines,
                )
            )
        return sections

    def _detect_structural_heading(self, line: str) -> tuple[int, str] | None:
        markdown_match = self.HEADING_RE.match(line)
        if markdown_match:
            title = self._plain_markdown(markdown_match.group(2))
            if self.PAGE_HEADING_RE.fullmatch(title):
                return None
            return len(markdown_match.group(1)), title

        stripped = line.strip()
        if (
            re.match(r"^(?:[-+*•]\s+)", stripped)
            or re.match(r"^\d+[.)]\s+\S.+[.!?]\s*$", stripped)
            or re.match(r"^.{1,100}(?::|：)\s+\S", stripped)
        ):
            return None

        plain = self._plain_markdown(line)
        numbered_match = self.NUMBERED_HEADING_RE.match(plain)
        if numbered_match:
            title = numbered_match.group("title").strip(" .:")
            if self._is_known_section_title(title):
                level = numbered_match.group("number").count(".") + 1
                return level, title

        if self._is_known_section_title(plain) and len(plain) <= 100:
            return 1, plain.strip(" .:")
        return None

    def _select_sections(
        self,
        sections: list[_CourseSection],
        anchors: Iterable[str],
    ) -> list[_CourseSection]:
        selected: list[_CourseSection] = []
        for section in sections:
            if not self._matches_any_anchor(section.title, anchors):
                continue
            if any(
                parent.start < section.start < parent.end
                for parent in selected
            ):
                continue
            selected.append(section)
        return selected

    def _paragraph_fallback(
        self,
        lines: list[str],
        anchors: Iterable[str],
    ) -> list[str]:
        paragraphs = self._extract_paragraphs(lines)
        return [
            paragraph
            for paragraph in paragraphs
            if self._contains_any_anchor(paragraph, anchors)
        ]

    @classmethod
    def _render_block(cls, lines: Iterable[str]) -> str:
        rendered: list[str] = []
        previous_blank = False

        for line in lines:
            stripped = line.strip()
            if not stripped:
                if rendered and not previous_blank:
                    rendered.append("")
                previous_blank = True
                continue

            plain = cls._plain_markdown(stripped)
            if not plain:
                continue

            if re.match(r"^\s*(?:[-+*•]\s+|\d+[.)]\s+)", stripped):
                rendered.append(stripped)
            else:
                rendered.append(plain)
            previous_blank = False

        while rendered and not rendered[-1]:
            rendered.pop()
        return "\n".join(rendered)

    def _is_known_section_title(self, value: str) -> bool:
        anchors = (
            *self.CONTENT_ANCHORS,
            *self.REQUIREMENT_ANCHORS,
            *self.FORMAT_ANCHORS,
            *self.DURATION_ANCHORS,
            *self.OTHER_SECTION_ANCHORS,
        )
        normalized = self._normalize_for_match(value)
        return any(
            normalized == self._normalize_for_match(anchor)
            for anchor in anchors
        )

    @staticmethod
    def _is_valid_course_name(value: str) -> bool:
        return (
            3 <= len(value) <= 180
            and not value.endswith(":")
            and not re.fullmatch(r"\d+", value)
        )

    @classmethod
    def _is_metadata_line(cls, value: str) -> bool:
        normalized = cls._normalize_for_match(value)
        prefixes = (
            "giang vien",
            "ngay cap nhat",
            "ngay",
            "ma khoa hoc",
            "khoa bo mon",
            "tai nguyen khoa hoc",
        )
        return any(normalized.startswith(prefix) for prefix in prefixes)

    @classmethod
    def _is_page_heading(cls, line: str) -> bool:
        match = cls.HEADING_RE.match(line)
        return bool(
            match
            and cls.PAGE_HEADING_RE.fullmatch(cls._plain_markdown(match.group(2)))
        )

    @classmethod
    def _deduplicate_values(
        cls,
        values: Iterable[str],
        existing_values: Iterable[str] = (),
    ) -> list[str]:
        kept: list[str] = []
        normalized_kept = [
            cls._normalize_for_match(value) for value in existing_values
        ]

        for value in values:
            cleaned = cls._plain_markdown(value).strip(" ;")
            normalized = cls._normalize_for_match(cleaned)
            if not normalized:
                continue
            if any(
                normalized in existing or existing in normalized
                for existing in normalized_kept
                if existing
            ):
                continue
            kept.append(cleaned)
            normalized_kept.append(normalized)
        return kept


def extract_course(cleaned_text: str) -> dict[str, str]:
    """Convenience wrapper for :class:`CourseExtractor`."""
    return CourseExtractor().extract(cleaned_text)

import json
import logging
import re
import unicodedata
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path



LOGGER = logging.getLogger(__name__)


class DocumentProcessingError(RuntimeError):
    """Raised when parsing, cleaning, classifying, or extraction fails."""


@dataclass(frozen=True, slots=True)
class ClassificationResult:
    document_type: str
    profile_score: int
    course_score: int
    matched_keywords: tuple[str, ...]


class DocumentTypeClassifier:
    """Classify cleaned Markdown using title and weighted anchor keywords."""

    PROFILE_KEYWORDS = {
        "hồ sơ nhu cầu học viên": 12,
        "hồ sơ học viên": 10,
        "phiếu nhu cầu học viên": 10,
        "thông tin học viên": 7,
        "họ và tên": 5,
        "họ tên học viên": 5,
        "số điện thoại": 3,
        "mục tiêu học tập": 2,
        "kỹ năng mong muốn": 4,
        "hình thức học mong muốn": 5,
        "thời gian có thể học": 5,
    }
    COURSE_KEYWORDS = {
        "thông tin khóa học": 12,
        "tên khóa học": 8,
        "mã khóa học": 6,
        "mô tả khóa học": 5,
        "nội dung đào tạo": 7,
        "nội dung chi tiết theo chương": 7,
        "kỹ năng đạt được": 5,
        "điều kiện tiên quyết": 6,
        "thời lượng khóa học": 6,
        "giảng viên": 4,
        "phương pháp đánh giá": 4,
    }

    def classify(self, cleaned_text: str, file_name: str = "") -> ClassificationResult:
        normalized_text = self._normalize(cleaned_text)
        normalized_title = self._normalize(self._title_zone(cleaned_text))
        normalized_file_name = self._normalize(Path(file_name).stem)

        profile_score, profile_matches = self._score(
            normalized_text,
            normalized_title,
            normalized_file_name,
            self.PROFILE_KEYWORDS,
        )
        course_score, course_matches = self._score(
            normalized_text,
            normalized_title,
            normalized_file_name,
            self.COURSE_KEYWORDS,
        )

        if profile_score == course_score:
            document_type = self._resolve_tie(normalized_text)
        else:
            document_type = (
                "learner_profile"
                if profile_score > course_score
                else "course_information"
            )

        return ClassificationResult(
            document_type=document_type,
            profile_score=profile_score,
            course_score=course_score,
            matched_keywords=tuple(
                dict.fromkeys([*profile_matches, *course_matches])
            ),
        )

    def _score(
        self,
        text: str,
        title: str,
        file_name: str,
        keywords: dict[str, int],
    ) -> tuple[int, list[str]]:
        score = 0
        matches: list[str] = []
        for keyword, weight in keywords.items():
            normalized_keyword = self._normalize(keyword)
            if normalized_keyword not in text:
                continue
            score += weight
            if normalized_keyword in title:
                score += weight
            if normalized_keyword in file_name:
                score += weight
            matches.append(keyword)
        return score, matches

    @staticmethod
    def _resolve_tie(text: str) -> str:
        profile_signals = sum(
            signal in text
            for signal in ("email", "so dien thoai", "ho va ten", "toi ten la")
        )
        course_signals = sum(
            signal in text
            for signal in ("ma khoa hoc", "giang vien", "hoc phi", "so buoi")
        )
        return (
            "learner_profile"
            if profile_signals > course_signals
            else "course_information"
        )

    @staticmethod
    def _title_zone(text: str) -> str:
        meaningful_lines: list[str] = []
        for line in text.splitlines():
            value = re.sub(r"^\s*#{1,6}\s*", "", line).strip()
            if not value or re.fullmatch(r"(?:page|trang)\s+\d+", value, re.I):
                continue
            meaningful_lines.append(value)
            if len(meaningful_lines) >= 12:
                break
        return "\n".join(meaningful_lines)

    @staticmethod
    def _normalize(value: str) -> str:
        decomposed = unicodedata.normalize("NFD", value.casefold())
        value_without_marks = "".join(
            character
            for character in decomposed
            if unicodedata.category(character) != "Mn"
        ).replace("đ", "d")
        return re.sub(r"[^a-z0-9]+", " ", value_without_marks).strip()


class DocumentProcessingService:
    """Orchestrate parser, cleaner, classifier, and field extractors."""

    COLLECTIONS = {
        "learner_profile": "student_profiles",
        "course_information": "course_info",
    }

    def __init__(
        self,
        parser_config: ParserConfig | None = None,
        parser: DocumentParser | None = None,
    ) -> None:
        self.parser = parser or DocumentParser(parser_config or ParserConfig())
        self.cleaner = DataCleaner()
        self.classifier = DocumentTypeClassifier()
        self.profile_extractor = ProfileExtractor()
        self.course_extractor = CourseExtractor()

    def process(self, file_path: str | Path, original_file_name: str) -> dict[str, object]:
        path = Path(file_path)
        try:
            raw_markdown = self.parser.parse(path)
            cleaned_markdown = self.cleaner.clean_markdown_text(raw_markdown)
            classification = self.classifier.classify(
                cleaned_markdown,
                file_name=original_file_name,
            )
            if classification.document_type == "learner_profile":
                extracted_data = self.profile_extractor.extract(cleaned_markdown)
            else:
                extracted_data = self.course_extractor.extract(cleaned_markdown)
        except Exception as exc:
            LOGGER.exception("Document processing failed for %s", original_file_name)
            raise DocumentProcessingError(
                f"Could not process document '{original_file_name}'."
            ) from exc

        return {
            "file_name": original_file_name,
            "document_type": classification.document_type,
            "collection_name": self.COLLECTIONS[classification.document_type],
            "classification": {
                "profile_score": classification.profile_score,
                "course_score": classification.course_score,
                "matched_keywords": list(classification.matched_keywords),
            },
            "data": extracted_data,
        }


def discover_documents(input_dir: Path) -> list[Path]:
    supported_extensions = DocumentParser.SUPPORTED_EXTENSIONS
    return sorted(
        (
            path
            for path in input_dir.rglob("*")
            if path.is_file() and path.suffix.lower() in supported_extensions
        ),
        key=lambda path: str(path.relative_to(input_dir)).casefold(),
    )


def run_pipeline(
    input_dir: str | Path,
    output_file: str | Path,
    *,
    parser_config: ParserConfig | None = None,
) -> dict[str, object]:
    """Batch entry point retained for offline processing and regression tests."""
    source_dir = Path(input_dir).expanduser().resolve()
    destination = Path(output_file).expanduser().resolve()
    if not source_dir.is_dir():
        raise FileNotFoundError(f"Input directory not found: {source_dir}")

    service = DocumentProcessingService(parser_config=parser_config)
    documents: list[dict[str, object]] = []
    errors: list[dict[str, str]] = []

    for document_path in discover_documents(source_dir):
        relative_path = document_path.relative_to(source_dir)
        try:
            processed = service.process(document_path, document_path.name)
            processed["relative_path"] = relative_path.as_posix()
            documents.append(processed)
        except DocumentProcessingError as exc:
            errors.append(
                {
                    "file_name": document_path.name,
                    "relative_path": relative_path.as_posix(),
                    "error": str(exc),
                }
            )

    payload: dict[str, object] = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "input_directory": str(source_dir),
        "total_documents": len(documents) + len(errors),
        "successful_documents": len(documents),
        "failed_documents": len(errors),
        "documents": documents,
        "errors": errors,
    }
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        json.dumps(payload, ensure_ascii=False, indent=4),
        encoding="utf-8",
    )
    return payload

class BackendDocumentModel:
    """Serializable facade consumed by the FastAPI backend."""

    MODEL_VERSION = "1.0.0"
    SUPPORTED_EXTENSIONS = tuple(sorted(DocumentParser.SUPPORTED_EXTENSIONS))

    def __init__(
        self,
        *,
        enable_ocr: bool = True,
        ocr_language: str = "vie+eng",
        tesseract_cmd: str | None = None,
        enable_marker: bool = False,
    ) -> None:
        self.configure(
            enable_ocr=enable_ocr,
            ocr_language=ocr_language,
            tesseract_cmd=tesseract_cmd,
            enable_marker=enable_marker,
        )

    def configure(
        self,
        *,
        enable_ocr: bool = True,
        ocr_language: str = "vie+eng",
        tesseract_cmd: str | None = None,
        enable_marker: bool = False,
    ) -> None:
        marker = MarkerPageFallback() if enable_marker else None
        self.service = DocumentProcessingService(
            parser_config=ParserConfig(
                enable_ocr=enable_ocr,
                ocr_language=ocr_language,
                tesseract_cmd=tesseract_cmd,
                advanced_fallback=marker,
            )
        )

    def predict(
        self,
        file_path: str | Path,
        file_name: str | None = None,
    ) -> dict[str, object]:
        path = Path(file_path)
        return self.service.process(path, file_name or path.name)


def create_model(**config: object) -> BackendDocumentModel:
    """Create the model instance used by the backend."""
    return BackendDocumentModel(**config)
